/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AdministrativeRole;

import business.CongestionProblem.CongestionProblem;
import business.CongestionProblem.CongestionProblemDirectory;
import business.Enterprise.Enterprise;
import business.Route.Route;
import business.Route.TemporaryRouteList;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

public class GraphicalRepresentationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private TemporaryRouteList temporaryRouteList;
    private CongestionProblemDirectory congestionProblemDirectory;

    /**
     * Creates new form GraphicalRepresentationJPanel
     */
    public GraphicalRepresentationJPanel(JPanel userProcessContainer, Enterprise enterprise, TemporaryRouteList temporaryRouteList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.temporaryRouteList=temporaryRouteList;
        congestionProblemDirectory=enterprise.getCongestionProblemDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCongestionRoute = new javax.swing.JButton();
        backJButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        btnCongestionRoute.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCongestionRoute.setText("Total Number of Congestions occured on each route");
        btnCongestionRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongestionRouteActionPerformed(evt);
            }
        });

        backJButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        backJButton1.setText("Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Graphical Representation:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton1)
                    .addComponent(jLabel1)
                    .addComponent(btnCongestionRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnCongestionRoute)
                .addGap(161, 161, 161)
                .addComponent(backJButton1)
                .addContainerGap(162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCongestionRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongestionRouteActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset chartData = new DefaultCategoryDataset();
        for (Route route : temporaryRouteList.getRouteList())
        {
            chartData.setValue(route.getProbCount(), "Number of Congestion Problems per Route", route.getRouteName());
        }

        JFreeChart barChart =ChartFactory.createBarChart("Number of Congestion Problems per Route", "Route", "Problem Occurence", chartData, PlotOrientation.VERTICAL,false, true, false);
        CategoryPlot chart = barChart.getCategoryPlot();
        
        chart.setRangeGridlinePaint(Color.GREEN);

        ChartPanel barPanel=new ChartPanel(barChart);
//        jPanel1.removeAll();
//        jPanel1.setVisible(true);
//        jPanel1.add(barPanel,BorderLayout.CENTER);
//        jPanel1.validate();
        
        ChartFrame frame=new ChartFrame("Bar chart for Problems per Route", barChart);
        frame.setVisible(true);
        frame.setSize(450, 350);

    }//GEN-LAST:event_btnCongestionRouteActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton btnCongestionRoute;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
