/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CommuterRole;

import business.CongestionProblem.CongestionProblemDirectory;
import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Location.LocationDirectory;
import business.Organization.CommuterOrganization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class CommuterWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private CommuterOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private LocationDirectory locationDirectory;
    private CongestionProblemDirectory congestionProblemDirectory;
    private EcoSystem business; 
    /**
     * Creates new form CarDriverWorkAreaJPanel
     */
//    public CommuterWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CommuterOrganization organization, Enterprise enterprise) {
//        initComponents();
//        this.userProcessContainer = userProcessContainer;
//        this.organization = organization;
//        this.enterprise = enterprise;
//        this.userAccount = account;
//        locationDirectory=enterprise.getLocationDirectory();
//        enterprise.addCongestionProblems();
//        congestionProblemDirectory=enterprise.getCongestionProblemDirectory();
//    }

    public CommuterWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CommuterOrganization commuterOrganization, Enterprise enterprise, EcoSystem business) {
       initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business=business;
        
        locationDirectory=enterprise.getLocationDirectory();
        enterprise.addCongestionProblems();
        
        congestionProblemDirectory=enterprise.getCongestionProblemDirectory();//To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGPS = new javax.swing.JButton();
        btnCongestionProblem = new javax.swing.JButton();
        btnGetInformation = new javax.swing.JButton();

        setBackground(new java.awt.Color(234, 176, 150));

        jPanel1.setBackground(new java.awt.Color(234, 176, 150));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel1.setText("Commuter Work Area:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Commuter.png"))); // NOI18N

        btnGPS.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnGPS.setText("GPS");
        btnGPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGPSActionPerformed(evt);
            }
        });

        btnCongestionProblem.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnCongestionProblem.setText("Congestion Problem");
        btnCongestionProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongestionProblemActionPerformed(evt);
            }
        });

        btnGetInformation.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnGetInformation.setText("Get Information");
        btnGetInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetInformationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCongestionProblem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGPS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGetInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGPS)
                        .addGap(18, 18, 18)
                        .addComponent(btnCongestionProblem)
                        .addGap(18, 18, 18)
                        .addComponent(btnGetInformation))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGPSActionPerformed
        GPSJPanel gPSJPanel = new GPSJPanel(userProcessContainer, congestionProblemDirectory, locationDirectory, userAccount);
        userProcessContainer.add("gPSJPanel", gPSJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnGPSActionPerformed

    private void btnCongestionProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongestionProblemActionPerformed
        CongestionProblemJPanel congestionProblemJPanel = new CongestionProblemJPanel(userProcessContainer, congestionProblemDirectory, locationDirectory, userAccount, enterprise,business);
        userProcessContainer.add("congestionProblemJPanel", congestionProblemJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCongestionProblemActionPerformed

    private void btnGetInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetInformationActionPerformed
        GetInformationJPanel getInformationJPanel= new GetInformationJPanel(userProcessContainer, congestionProblemDirectory, locationDirectory, userAccount);
        userProcessContainer.add("getInformationJPanel", getInformationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnGetInformationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCongestionProblem;
    private javax.swing.JButton btnGPS;
    private javax.swing.JButton btnGetInformation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
