/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CommuterRole;

import business.CongestionProblem.CongestionProblemDirectory;
import business.Enterprise.Enterprise;
import business.Location.LocationDirectory;
import business.Organization.CommuterOrganization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class CommuterWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private CommuterOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private LocationDirectory locationDirectory;
    private CongestionProblemDirectory congestionProblemDirectory;
    /**
     * Creates new form CarDriverWorkAreaJPanel
     */
    public CommuterWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CommuterOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        locationDirectory=enterprise.getLocationDirectory();
        enterprise.addCongestionProblems();
        congestionProblemDirectory=enterprise.getCongestionProblemDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnGPS = new javax.swing.JButton();
        btnCongestionProblem = new javax.swing.JButton();

        setBackground(new java.awt.Color(234, 176, 150));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel1.setText("Car Driver Work Area:");

        btnGPS.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnGPS.setText("GPS");
        btnGPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGPSActionPerformed(evt);
            }
        });

        btnCongestionProblem.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btnCongestionProblem.setText("Congestion Problem");
        btnCongestionProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongestionProblemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(btnCongestionProblem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGPS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addComponent(btnGPS)
                .addGap(38, 38, 38)
                .addComponent(btnCongestionProblem)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGPSActionPerformed
        GPSJPanel gPSJPanel = new GPSJPanel(userProcessContainer, congestionProblemDirectory, locationDirectory, userAccount);
        userProcessContainer.add("gPSJPanel", gPSJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnGPSActionPerformed

    private void btnCongestionProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongestionProblemActionPerformed
        CongestionProblemJPanel congestionProblemJPanel = new CongestionProblemJPanel(userProcessContainer, congestionProblemDirectory, locationDirectory, userAccount, enterprise);
        userProcessContainer.add("congestionProblemJPanel", congestionProblemJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCongestionProblemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCongestionProblem;
    private javax.swing.JButton btnGPS;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
